# numpy notları

<!-- numpy ile çalışma -->

In [1]:
import numpy as np


# result=np.array([ 1,3,6,9])
# dizi içine kendimiz tanımlama yapmak istemezsek bu komutları kullanabiliriz
#result =np.arange(1,10) 
#result =np.arange(10,100,3) 10 dan 100 e kadar 3 er artarak ekler 
#result=np.zeros(10) 10 tane 0 ekler 
#result=np.ones(10)# 10 tane 1 ekler 
# result=np.linspace(0,100,5) 0 dan 100e kadar değerleri eşit aralıklarda böler

# result= np.random.randint(10) # rastgel sayı üretir
#result=np.random.randint(1,10,3) # tane rastgele sayı üretir 

# result= np.random.rand(3) 3 tane 0-1 arası sayı üretir

"""np_array=np.arange(50)
np_multi = np_array.reshape(5,10)


print(np_multi.sum(axis=1)) # 1 . satırların toplamını verir
print(np_multi.sum(axis=0)) # sütunların toplamını verir"""


rnd_numbers =np.random.randint(1,100,10)
print(rnd_numbers)
result=rnd_numbers.min()
print("min deger",result)
result=rnd_numbers.max()
print('max deger',result)
result=rnd_numbers.mean() # sayıların ortalamasını verir
print(result)
result=rnd_numbers.argmax()# en büyük sayının indexini verir
print(result)
result=rnd_numbers.argmin()# tam tersi
print(result)

[30 63 32 10 14 38 45 45 90 57]
min deger 10
max deger 90
42.4
8
3


<!-- numpy dizilerinin indexlenmesi -->

In [661]:
import numpy as np

"""# elemanlara ulaşma kısmı liste mantığı ile aynı
numbers= np.arange(0,76,5)
result=numbers[5]
print(numbers)
print(result)
print(numbers[:3])
print(numbers[3:])"""

numbers =numbers.reshape(4,4)
print("*****************")
print(numbers)
print("*****************")
#result=numbers[2,3] 2. satırın 3. elemanını aldık

result=numbers[:,2]# tüm satırlardan 2. indextekileri aldık
print("*****************")
print(result)
print("*****************")
result=numbers[:,:2]# tüm satırlardan 0-2 arasındakileri al
print(result)
result=numbers[-1,:]# sonuncu satrın tüm elemanları
print("*****************")
print(result)
print("*****************")


arr1= np.arange(0,10)
arr2=arr1 # referans koyalaması yaptık aynı adres farklı tanım
arr2[0]=35
print(arr1)
print(arr2)
print("*****************")

arr2[0]=35


arr2=arr1.copy() # burda farklı adreste farklı dizi yaptık

arr2[0]=25
print(arr1)
print(arr2)

*****************
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]
 [60 65 70 75]]
*****************
*****************
[10 30 50 70]
*****************
[[ 0  5]
 [20 25]
 [40 45]
 [60 65]]
*****************
[60 65 70 75]
*****************
[35  1  2  3  4  5  6  7  8  9]
[35  1  2  3  4  5  6  7  8  9]
*****************
[35  1  2  3  4  5  6  7  8  9]
[25  1  2  3  4  5  6  7  8  9]


<!-- numpy dizi operasyonları -->


In [2]:
import numpy as np

numbers1=np.random.randint(10,100,6)
numbers2=np.random.randint(10,100,6)

print(numbers1)
print(numbers2)
# toplama çıkarma çarpma bölme yapabiliriz
result =numbers1+numbers2

print(result)
print("*****************")

result =numbers1+10 # her elemana 10 ekler

print(result)

result=numbers1-numbers2

print(result)
print("*****************")

# matematiksel işlemleri
result=np.sin(numbers1) 
print(result)
result=np.log(numbers1) 
print(result)

print("*****************")



mnumbers1= numbers1.reshape(2,3)
mnumbers2= numbers2.reshape(2,3)

print(mnumbers1)
print("*****************")
print(mnumbers2)
print("*****************")

print(np.vstack((mnumbers1,mnumbers2))) # iki matrisi dikey olarak birleştirdi

print("*****************")

print(np.hstack((mnumbers1,mnumbers2)))# yatay olarak birleştirdi


print("*****************")



result= numbers1 >=50 # bool çıktısı verir
print(result)
print("*****************")
result=numbers2 %2==0

print(numbers2[result])# result koşul cevabı olduğu için true olanları yazdırdı
print(result)


[22 63 60 43 21 85]
[49 97 82 27 64 99]
[ 71 160 142  70  85 184]
*****************
[32 73 70 53 31 95]
[-27 -34 -22  16 -43 -14]
*****************
[-0.00885131  0.1673557  -0.30481062 -0.83177474  0.83665564 -0.17607562]
[3.09104245 4.14313473 4.09434456 3.76120012 3.04452244 4.44265126]
*****************
[[22 63 60]
 [43 21 85]]
*****************
[[49 97 82]
 [27 64 99]]
*****************
[[22 63 60]
 [43 21 85]
 [49 97 82]
 [27 64 99]]
*****************
[[22 63 60 49 97 82]
 [43 21 85 27 64 99]]
*****************
[False  True  True False False  True]
*****************
[82 64]
[False False  True False  True False]


<!-- uygulama -->

In [55]:
import numpy as np

np_array=np.array([10,15,30,45,60]) # numpy dizisi
np_array=np.arange(5,15)# 5-15 arsı sayıları ekleme
np_array=np.arange(50,100,5)#50-100 arası sayıları beşer beşer ekleme
np_array=np.zeros(10) # on adet 0 ekleme 
np_array=np.ones(10)# on adet 1 ekleme 
np_array=np.linspace(0,100,5)# 0 -100 arası rastgele 5 eşit aralıkta
np_array=np.random.randint(10,30,5)#0-30 arası 5 sayı ekleme
np_array=np.random.randn(5)# -1 ile 1 aarsında 5 sayı ekleme
np_array=np.random.randint(-50,50,15).reshape(3,5)# 3x5 lik rastgele matris
s_toplam=np_array.sum(axis=1) # satır toplam 
s_toplam=np_array.sum(axis=0) # sütun toplam

min=np_array.min() # min değer 
max=np_array.max()# max değer

ort=np_array.mean()# ortalamayı verir
print(np_array)
print(np_array.argmax())# en büyük sayıının indexini verir
print(np_array.argmin())# en küçük sayının indexini verir
print("*****************")
print(ort)

"""arr=np.arange(10,20)
print(arr[:3])
print(arr[::-1])"""
print(np_array[2,3])
print(np_array[:,0])
kare=np_array**2
print(kare)
print("*****************")
print(np_array[np_array%2==0]) # çift sayıları yazar

print("*****************")
result= np_array[np_array%2==1]# tek sayıları yazar
print(result[result>0])

[[-45   0   1   9  -1]
 [ 29 -29 -20 -29 -13]
 [ 31  -8  -4 -45  -1]]
10
0
*****************
-8.333333333333334
-45
[-45  29  31]
[[2025    0    1   81    1]
 [ 841  841  400  841  169]
 [ 961   64   16 2025    1]]
*****************
[  0 -20  -8  -4]
*****************
[ 1  9 29 31]
